/**
 * Static dictionaries under `/content/translations` (generated by `scripts/sync-content-translations.mjs`).
 */
import { routing } from '@/i18n/routing';
import { getDictionary } from '@/lib/translations';

export const messagesByLocale: Record<string, Record<string, unknown>> = {
  en: getDictionary('en') as Record<string, unknown>,
  te: getDictionary('te') as Record<string, unknown>,
  hi: getDictionary('hi') as Record<string, unknown>,
  es: getDictionary('es') as Record<string, unknown>,
};

export function getMessagesForLocale(locale: string): Record<string, unknown> {
  if (routing.locales.includes(locale as (typeof routing.locales)[number])) {
    return messagesByLocale[locale];
  }
  return messagesByLocale.en;
}

export type BlogMessages = {
  title: string;
  subtitle: string;
  /** Optional editorial note on listing pages (AdSense / trust signals). */
  intro?: string;
  readMore: string;
  backToBlog: string;
  relatedPosts?: string;
  categories?: string;
  recentPosts?: string;
  posts: Record<
    string,
    { title: string; excerpt: string; category: string; readTime: string; content?: string }
  >;
};

export function getBlogMessages(locale: string): BlogMessages | null {
  const messages = getMessagesForLocale(locale);
  const blog = messages?.Blog;
  if (blog && typeof blog === 'object' && blog !== null && 'posts' in blog) {
    return blog as unknown as BlogMessages;
  }
  return null;
}
